part1:
	tsc day9_part1.ts
	node day9_part1.js
	rm -rf ./day9_part1.js ./package-lock.json ./package.json ./tsconfig.json  
	rm -rf ./node_modules/
part2:
	tsc day9_part2.ts
	node day9_part2.js
	rm -rf ./day9_part2.js ./package-lock.json ./package.json ./tsconfig.json
	rm -rf ./node_modules/
